name: Stop spam
on:
  # Triggers the workflow on pull request open event but only for the "main" branch
  pull_request:
    types: [opened]
    branches: ["main"]
permissions:
  issues: write
  pull-requests: write
jobs:
  github_spamstop_job:
    runs-on: ubuntu-latest
    name: A job to detect spam PR
    steps:
      - name: Detect Spam PR
        uses: animesh-chouhan/github-spamstop@main
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
